### ISSUE TITLE
HD5 Support

### ISSUE THREAD

**Issue by Tarskin** [Tarskin/LaCyTools#2]
Integrate HD5 support in LaCyTools

**Comment by magnuspalmblad** [comment]
Why are we reimplementing his? Or more precisely: how is this different than [mz5](http://software.steenlab.org/mz5/) from the Steen lab, which is already in ProteoWizard?

**Comment by genadijrazdorov** [comment]
mz5 is replicating xml formats with hd5 library, and it doesn't use [pytables](http://www.pytables.org/), which is more then just a python wrapper for hd5, and it doesn't use [blosc](http://www.blosc.org/), an extremely fast, multi-threaded, meta-compressor library.
LacyTools is using both libraries and not just replicating xml ways, so it is fast and uses only 1/3 of disk space.

**Comment by magnuspalmblad** [comment]
OK - I (genuinely) look forward to a side-by-side comparison! There are so many ways to put the data in mzML too (just looking at msconvert), which also have a huge effect on size. But I suspect you are aware of these!

Will you be at ASMS or IMSC? Otherwise, perhaps I will see you in Leiden sometime?

**Comment by genadijrazdorov** [comment]
Fair comparison is absolutely in our plans. 

This is my last day in Leiden. I will probably not be at the ASMS or IMSC this year.
